name: arcane_inkwell_example
description: Example knowledge base using arcane_inkwell
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  web: ^1.1.1
  arcane_inkwell:
    path: ../
  jaspr: ^0.22.1
  jaspr_content: ^0.4.5

dev_dependencies:
  build_runner: ^2.10.4
  build_web_compilers: ^4.4.6
  jaspr_builder: ^0.22.1
  lints: ^6.0.0

jaspr:
  mode: server

scripts:
  serve: jaspr serve
  build: jaspr build
  clean: jaspr clean
